### ISSUE TITLE
search weirdness - browser dependent ??

### ISSUE THREAD

**Issue by SamsTheNerd** [3eef8a28f26fb2bcc514e6f1938929a1f931762/quatalog#9]
maybe sorting function doesn't work ? idk
chrome doesn't give the right results. 
example: search "algo" gives intro algorithms in firefox but approx algorithms in chrome. maybe sort function isn't working?

**Comment by powe97** [comment]
solution: delete the search page

**Comment by powe97** [comment]
Solved: the sort function was returning 0 when it was supposed to return -1 in the following codeblock. 0 indicates "equal" while -1 indicates "less than." Chrome and Firefox seemed to do different things when 0 was returned.
```
    validResults.sort((a,b)=>{
        if(a.score - b.score > 0.05){
            return 1;
        } else if(b.score - a.score > 0.05){
            return -1;
        }
        return a.item.crse > b.item.crse; // HERE
    })
```
The fix:
```
        return (a.item.crse > b.item.crse) || -1;
````
